### ISSUE TITLE
Extend ResourceExtractor to handle folders of resources

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Commons#10]
In ET_Redux, we keep serialized XML model files as resources in directories related to the model's class.  The number and names of the files vary over time.  The current behavior of ResourceExtractor is to assume a resource is a file (see extractResourceAsFile()) even though the type returned is type File, which can include directories.  The proposed behavior would extend ResourceExtractor to handle directories by the same technique as used for files - making a temporary copy of the whole directory possibly to any depth - since nio.file.Files supports creating temporary directories as well.

@johnzeringue please comment.

**Comment by johnzeringue** [comment]
This is certainly possible, though maybe not so easy. As I understand it, the class loader is very file-oriented. Directories aren't even considered resources. If someone's willing to work on it, though, I think it's a good improvement. In order to keep the interface consistent, `ResourceExtractor#extractResourceAsPath(String)` should exhibit the new behavior as well.

@bowring, is this sort of functionality in production now? If not, what's the use case motivating the change?

**Comment by bowring** [comment]
@johnzeringue - it is in production using the split handler for IDE and jar file scenarios.  The folder is merely a container for a set of xml model files that are each a resource.  The folder is not a resource per se but a specific location in which to find serialized files of a certain class.  This indirection means that ET_Redux is agnostic as what specific files these are, expecting only that they might exist.

**Comment by bowring** [comment]
@johnzeringue - Solution: have a known resource file that contains a list of the other resource files = index.  Access index, use it to get the listed resources.  Thoughts?

**Comment by johnzeringue** [comment]
I don't think there's any problem with that. If you were really adding resources _en masse_, it would even be easy to write a script to generate this index automatically. An alternative would be to incorporate SQLite and just distribute a single DB file. That would add quite a bit of complexity, though.

Since those both seem like better, more stable solutions, let's scratch this issue.
